before_script:
    - source /tools/setup.sh
    - export PYTHONPATH=$(pwd)
    - python3 -m pip install six
    - python3 -m aapg.main setup; rm config.ini

test:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_eclass_rv64imac_bringup.ini
        - timeout 30 make ISA=rv64imac
        - python3 -m aapg.main gen --arch rv32 --config $PWD/samples/shakti_configs/aapg_eclass_rv32imac_bringup.ini
        - timeout 30 make ISA=rv32imac ABI=ilp32
    only:
        - master
    tags:
        - shakti-runner
