image: iitmshakti/riscv-dev:0.5.0

before_script:
    - export PYTHONPATH=$(pwd)
    - python3 -m pip install six
    - python3 -m aapg.main setup; rm config.ini

conf1_rv64:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_eclass_bringup.ini
        - timeout 30 make
    only:
        - master
    tags:
        - anmol-local

conf2_rv64:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_cclass_bringup.ini
        - timeout 30 make
    only:
        - master
    tags:
        - anmol-local

conf3_rv64:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_cclass_config1.ini
        - timeout 30 make
    only:
        - master
    tags:
        - anmol-local

conf4_rv64:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_igcar_bringup.ini
        - timeout 30 make
    only:
        - master
    tags:
        - anmol-local

conf1_rv32:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_eclass_bringup.ini --arch rv32
        - timeout 30 make ISA=rv32imafd ABI=ilp32
    only:
        - master
    tags:
        - anmol-local

conf2_rv32:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_cclass_bringup.ini --arch rv32
        - timeout 30 make ISA=rv32imafd ABI=ilp32
    only:
        - master
    tags:
        - anmol-local

conf3_rv32:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_cclass_config1.ini --arch rv32
        - timeout 30 make ISA=rv32imafd ABI=ilp32
    only:
        - master
    tags:
        - anmol-local

conf4_rv32:
    script:
        - python3 -m aapg.main gen --config $PWD/samples/shakti_configs/aapg_igcar_bringup.ini --arch rv32
        - timeout 30 make ISA=rv32imafd ABI=ilp32
    only:
        - master
    tags:
        - anmol-local
