stages:
  - pre-merge
  - deploy

pre-merge:
  stage: pre-merge
    script:
        - source /tools/setup.sh
        - export PYTHONPATH=$(pwd)
        - export PATH="/home/lavanya/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
        - eval "$(pyenv virtualenv-init -)"
        - pyenv activate py37
        - pip install pytest
        - pip install pytest-timeout
        - pip uninstall -y aapg
        - python setup.py install
        - pytest tests/test_aapg.py -m "serial" -v
        - pytest tests/test_aapg.py -n 10 -m "not serial" -v --seed=$((1 + $RANDOM)) -s
    tags:
        - mathsya-shakti
    only:
        refs:
            - merge_requests


deploy:
    stage: deploy
    script:
        - source /tools/setup.sh
        - export PYTHONPATH=$(pwd)
        - export PATH="/home/lavanya/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
        - eval "$(pyenv virtualenv-init -)"
        - pyenv activate py37
        - pip install twine
        - python setup.py sdist
        - python -m twine upload --username $shaktipypiusername --password $shaktipypipassword dist/*
#        - python /scratch/version-extract-rst.py
    only:
        refs:
            - master
    tags:
        - mathsya-shakti


