stages:
  - test
  - test_master
  - deploy

before_script:
    - source /tools/setup_new.sh
    - export PYTHONPATH=$(pwd)
    - export PATH="/home/lavanya/.pyenv/bin:$PATH"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"
    - pyenv activate py37
    - pip install pytest
    - pip install pytest-timeout
    - pip uninstall -y aapg
    - python setup.py install
test:
    script:
        - pytest tests/test_aapg.py -m "serial" -v
        - pytest tests/test_aapg.py -m "not serial" -v --seed=$((1 + $RANDOM)) -s
    only:
        refs:
            - merge_requests
    tags:
        - mathsya-runner

test_master:
    script:
        - pytest tests/test_aapg.py -m "serial" -v
        - pytest tests/test_aapg.py -m "not serial" -v --seed=$((1 + $RANDOM)) -s
    only:
        refs:
            - master
    tags:
        - mathsya-runner

deploy:
    stage: deploy
    script:
        - source /tools/setup_new.sh
        - export PYTHONPATH=$(pwd)
        - export PATH="/home/lavanya/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
        - eval "$(pyenv virtualenv-init -)"
        - pyenv activate py37
        - pip install twine
        - python setup.py sdist
        - python -m twine upload --username $shaktipypiusername --password $shaktipypipassword dist/*
#        - python /scratch/version-extract-rst.py
    only:
        refs:
            - master
    tags:
        - mathsya-runner

